# Generated by Django 4.2.4 on 2023-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
