# Generated by Django 4.2.4 on 2023-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_usermodel_about_usermodel_address_usermodel_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="about",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="zip/code",
            field=models.IntegerField(null=True),
        ),
    ]
