# Generated by Django 4.2.4 on 2023-09-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_usermodel_about_alter_usermodel_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="country",
            field=models.CharField(
                choices=[
                    ("us", "United States"),
                    ("ca", "Canada"),
                    ("uk", "United Kingdom"),
                    ("au", "Australia"),
                    ("fr", "France"),
                    ("de", "Germany"),
                    ("jp", "Japan"),
                    ("vn", "Viet Nam"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
