# Generated by Django 4.2.4 on 2023-09-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_usermodel_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="avatar",
            field=models.ImageField(null=True, upload_to="accounts"),
        ),
    ]
