# Generated by Django 4.2.4 on 2023-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_usermodel_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="zip/code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
