# Generated by Django 4.2.4 on 2023-09-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_usermodel_zip_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermodel", name="zip/code",),
        migrations.AddField(
            model_name="usermodel",
            name="zip_code",
            field=models.IntegerField(blank=True, db_column="Zip Code", null=True),
        ),
    ]
