# Generated by Django 4.2.4 on 2023-09-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_blacklistedtokenmodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="blacklistedtokenmodel", name="user",),
    ]
