@urlDev = http://127.0.0.1:8000/home



POST {{urlDev}}
Content-Type: application/json

{
    "email": "mrkonsungmail.com",
    "password": "Ngoidfsdf34@"
}
###
GET {{urlDev}}
Content-Type: application/json
