@urlDev = http://127.0.0.1:8000/api/v1



POST {{urlDev}}
Content-Type: application/json

{
    "email": "mrkonsun@gmail.com",
    "password": "Ngoidfsdf34@"
}
###
GET {{urlDev}}
Content-Type: application/json
